name: requests
description: a flutter library that helps with http requests and stored cookies
version: 3.1.2
homepage: https://github.com/jossef/requests
authors:
- Jossef Harush <jossef12@gmail.com>
- Rick Stanley <rick-stanley@hotmail.com>
- Martin <https://github.com/genesiscz>
- Frederik Pietzko <pietzkof@gmail.com>
- Rafael Carvalho Monteiro <rafael@qwkin.io>
- eggate <https://github.com/eggate>
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  http: ^0.13.0
  shared_preferences: ^2.0.3
  crypto: ^3.0.0
  hex: ^0.1.2
  logging: ^1.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.0.0

